[build]
  command = "npm run build:netlify:simple"
  publish = "client/dist"
  functions = "api"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "api"
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "bcryptjs", "jsonwebtoken"]
  included_files = ["api/**/*"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

