// Country flags utility for bot marketplace
// Based on world.db.flags repository with all available countries

export const countryFlags = {
  // North America
  US: { name: 'United States', code: 'us', region: 'North America' },
  CA: { name: 'Canada', code: 'ca', region: 'North America' },
  MX: { name: 'Mexico', code: 'mx', region: 'North America' },
  
  // Europe
  GB: { name: 'United Kingdom', code: 'gb', region: 'Europe' },
  DE: { name: 'Germany', code: 'de', region: 'Europe' },
  FR: { name: 'France', code: 'fr', region: 'Europe' },
  IT: { name: 'Italy', code: 'it', region: 'Europe' },
  ES: { name: 'Spain', code: 'es', region: 'Europe' },
  NL: { name: 'Netherlands', code: 'nl', region: 'Europe' },
  BE: { name: 'Belgium', code: 'be', region: 'Europe' },
  CH: { name: 'Switzerland', code: 'ch', region: 'Europe' },
  AT: { name: 'Austria', code: 'at', region: 'Europe' },
  SE: { name: 'Sweden', code: 'se', region: 'Europe' },
  NO: { name: 'Norway', code: 'no', region: 'Europe' },
  DK: { name: 'Denmark', code: 'dk', region: 'Europe' },
  FI: { name: 'Finland', code: 'fi', region: 'Europe' },
  PL: { name: 'Poland', code: 'pl', region: 'Europe' },
  CZ: { name: 'Czech Republic', code: 'cz', region: 'Europe' },
  HU: { name: 'Hungary', code: 'hu', region: 'Europe' },
  RO: { name: 'Romania', code: 'ro', region: 'Europe' },
  BG: { name: 'Bulgaria', code: 'bg', region: 'Europe' },
  HR: { name: 'Croatia', code: 'hr', region: 'Europe' },
  SI: { name: 'Slovenia', code: 'si', region: 'Europe' },
  SK: { name: 'Slovakia', code: 'sk', region: 'Europe' },
  LT: { name: 'Lithuania', code: 'lt', region: 'Europe' },
  LV: { name: 'Latvia', code: 'lv', region: 'Europe' },
  EE: { name: 'Estonia', code: 'ee', region: 'Europe' },
  IE: { name: 'Ireland', code: 'ie', region: 'Europe' },
  PT: { name: 'Portugal', code: 'pt', region: 'Europe' },
  GR: { name: 'Greece', code: 'gr', region: 'Europe' },
  CY: { name: 'Cyprus', code: 'cy', region: 'Europe' },
  MT: { name: 'Malta', code: 'mt', region: 'Europe' },
  LU: { name: 'Luxembourg', code: 'lu', region: 'Europe' },
  IS: { name: 'Iceland', code: 'is', region: 'Europe' },
  RU: { name: 'Russia', code: 'ru', region: 'Europe' },
  UA: { name: 'Ukraine', code: 'ua', region: 'Europe' },
  BY: { name: 'Belarus', code: 'by', region: 'Europe' },
  MD: { name: 'Moldova', code: 'md', region: 'Europe' },
  AL: { name: 'Albania', code: 'al', region: 'Europe' },
  MK: { name: 'North Macedonia', code: 'mk', region: 'Europe' },
  ME: { name: 'Montenegro', code: 'me', region: 'Europe' },
  RS: { name: 'Serbia', code: 'rs', region: 'Europe' },
  BA: { name: 'Bosnia and Herzegovina', code: 'ba', region: 'Europe' },
  TR: { name: 'Turkey', code: 'tr', region: 'Europe' },
  
  // Asia
  JP: { name: 'Japan', code: 'jp', region: 'Asia' },
  CN: { name: 'China', code: 'cn', region: 'Asia' },
  KR: { name: 'South Korea', code: 'kr', region: 'Asia' },
  IN: { name: 'India', code: 'in', region: 'Asia' },
  SG: { name: 'Singapore', code: 'sg', region: 'Asia' },
  MY: { name: 'Malaysia', code: 'my', region: 'Asia' },
  TH: { name: 'Thailand', code: 'th', region: 'Asia' },
  VN: { name: 'Vietnam', code: 'vn', region: 'Asia' },
  PH: { name: 'Philippines', code: 'ph', region: 'Asia' },
  ID: { name: 'Indonesia', code: 'id', region: 'Asia' },
  TW: { name: 'Taiwan', code: 'tw', region: 'Asia' },
  HK: { name: 'Hong Kong', code: 'hk', region: 'Asia' },
  MO: { name: 'Macau', code: 'mo', region: 'Asia' },
  BD: { name: 'Bangladesh', code: 'bd', region: 'Asia' },
  PK: { name: 'Pakistan', code: 'pk', region: 'Asia' },
  LK: { name: 'Sri Lanka', code: 'lk', region: 'Asia' },
  NP: { name: 'Nepal', code: 'np', region: 'Asia' },
  MM: { name: 'Myanmar', code: 'mm', region: 'Asia' },
  KH: { name: 'Cambodia', code: 'kh', region: 'Asia' },
  LA: { name: 'Laos', code: 'la', region: 'Asia' },
  MN: { name: 'Mongolia', code: 'mn', region: 'Asia' },
  KZ: { name: 'Kazakhstan', code: 'kz', region: 'Asia' },
  UZ: { name: 'Uzbekistan', code: 'uz', region: 'Asia' },
  KG: { name: 'Kyrgyzstan', code: 'kg', region: 'Asia' },
  TJ: { name: 'Tajikistan', code: 'tj', region: 'Asia' },
  TM: { name: 'Turkmenistan', code: 'tm', region: 'Asia' },
  AF: { name: 'Afghanistan', code: 'af', region: 'Asia' },
  IR: { name: 'Iran', code: 'ir', region: 'Asia' },
  IQ: { name: 'Iraq', code: 'iq', region: 'Asia' },
  SY: { name: 'Syria', code: 'sy', region: 'Asia' },
  LB: { name: 'Lebanon', code: 'lb', region: 'Asia' },
  JO: { name: 'Jordan', code: 'jo', region: 'Asia' },
  IL: { name: 'Israel', code: 'il', region: 'Asia' },
  PS: { name: 'Palestine', code: 'ps', region: 'Asia' },
  SA: { name: 'Saudi Arabia', code: 'sa', region: 'Asia' },
  AE: { name: 'United Arab Emirates', code: 'ae', region: 'Asia' },
  QA: { name: 'Qatar', code: 'qa', region: 'Asia' },
  KW: { name: 'Kuwait', code: 'kw', region: 'Asia' },
  BH: { name: 'Bahrain', code: 'bh', region: 'Asia' },
  OM: { name: 'Oman', code: 'om', region: 'Asia' },
  YE: { name: 'Yemen', code: 'ye', region: 'Asia' },
  
  // Oceania
  AU: { name: 'Australia', code: 'au', region: 'Oceania' },
  NZ: { name: 'New Zealand', code: 'nz', region: 'Oceania' },
  FJ: { name: 'Fiji', code: 'fj', region: 'Oceania' },
  PG: { name: 'Papua New Guinea', code: 'pg', region: 'Oceania' },
  SB: { name: 'Solomon Islands', code: 'sb', region: 'Oceania' },
  VU: { name: 'Vanuatu', code: 'vu', region: 'Oceania' },
  NC: { name: 'New Caledonia', code: 'nc', region: 'Oceania' },
  PF: { name: 'French Polynesia', code: 'pf', region: 'Oceania' },
  
  // Africa
  ZA: { name: 'South Africa', code: 'za', region: 'Africa' },
  EG: { name: 'Egypt', code: 'eg', region: 'Africa' },
  NG: { name: 'Nigeria', code: 'ng', region: 'Africa' },
  KE: { name: 'Kenya', code: 'ke', region: 'Africa' },
  GH: { name: 'Ghana', code: 'gh', region: 'Africa' },
  ET: { name: 'Ethiopia', code: 'et', region: 'Africa' },
  UG: { name: 'Uganda', code: 'ug', region: 'Africa' },
  TZ: { name: 'Tanzania', code: 'tz', region: 'Africa' },
  DZ: { name: 'Algeria', code: 'dz', region: 'Africa' },
  MA: { name: 'Morocco', code: 'ma', region: 'Africa' },
  TN: { name: 'Tunisia', code: 'tn', region: 'Africa' },
  LY: { name: 'Libya', code: 'ly', region: 'Africa' },
  SD: { name: 'Sudan', code: 'sd', region: 'Africa' },
  SS: { name: 'South Sudan', code: 'ss', region: 'Africa' },
  CM: { name: 'Cameroon', code: 'cm', region: 'Africa' },
  CI: { name: 'Ivory Coast', code: 'ci', region: 'Africa' },
  SN: { name: 'Senegal', code: 'sn', region: 'Africa' },
  ML: { name: 'Mali', code: 'ml', region: 'Africa' },
  BF: { name: 'Burkina Faso', code: 'bf', region: 'Africa' },
  NE: { name: 'Niger', code: 'ne', region: 'Africa' },
  TD: { name: 'Chad', code: 'td', region: 'Africa' },
  CF: { name: 'Central African Republic', code: 'cf', region: 'Africa' },
  CG: { name: 'Republic of the Congo', code: 'cg', region: 'Africa' },
  CD: { name: 'Democratic Republic of the Congo', code: 'cd', region: 'Africa' },
  AO: { name: 'Angola', code: 'ao', region: 'Africa' },
  ZM: { name: 'Zambia', code: 'zm', region: 'Africa' },
  ZW: { name: 'Zimbabwe', code: 'zw', region: 'Africa' },
  BW: { name: 'Botswana', code: 'bw', region: 'Africa' },
  NA: { name: 'Namibia', code: 'na', region: 'Africa' },
  SZ: { name: 'Eswatini', code: 'sz', region: 'Africa' },
  LS: { name: 'Lesotho', code: 'ls', region: 'Africa' },
  MG: { name: 'Madagascar', code: 'mg', region: 'Africa' },
  MU: { name: 'Mauritius', code: 'mu', region: 'Africa' },
  SC: { name: 'Seychelles', code: 'sc', region: 'Africa' },
  RW: { name: 'Rwanda', code: 'rw', region: 'Africa' },
  BI: { name: 'Burundi', code: 'bi', region: 'Africa' },
  DJ: { name: 'Djibouti', code: 'dj', region: 'Africa' },
  SO: { name: 'Somalia', code: 'so', region: 'Africa' },
  ER: { name: 'Eritrea', code: 'er', region: 'Africa' },
  GM: { name: 'Gambia', code: 'gm', region: 'Africa' },
  GW: { name: 'Guinea-Bissau', code: 'gw', region: 'Africa' },
  GN: { name: 'Guinea', code: 'gn', region: 'Africa' },
  SL: { name: 'Sierra Leone', code: 'sl', region: 'Africa' },
  LR: { name: 'Liberia', code: 'lr', region: 'Africa' },
  TG: { name: 'Togo', code: 'tg', region: 'Africa' },
  BJ: { name: 'Benin', code: 'bj', region: 'Africa' },
  GA: { name: 'Gabon', code: 'ga', region: 'Africa' },
  GQ: { name: 'Equatorial Guinea', code: 'gq', region: 'Africa' },
  ST: { name: 'São Tomé and Príncipe', code: 'st', region: 'Africa' },
  CV: { name: 'Cape Verde', code: 'cv', region: 'Africa' },
  MR: { name: 'Mauritania', code: 'mr', region: 'Africa' },
  EH: { name: 'Western Sahara', code: 'eh', region: 'Africa' },
  
  // South America
  BR: { name: 'Brazil', code: 'br', region: 'South America' },
  AR: { name: 'Argentina', code: 'ar', region: 'South America' },
  CL: { name: 'Chile', code: 'cl', region: 'South America' },
  PE: { name: 'Peru', code: 'pe', region: 'South America' },
  CO: { name: 'Colombia', code: 'co', region: 'South America' },
  VE: { name: 'Venezuela', code: 've', region: 'South America' },
  EC: { name: 'Ecuador', code: 'ec', region: 'South America' },
  BO: { name: 'Bolivia', code: 'bo', region: 'South America' },
  PY: { name: 'Paraguay', code: 'py', region: 'South America' },
  UY: { name: 'Uruguay', code: 'uy', region: 'South America' },
  GY: { name: 'Guyana', code: 'gy', region: 'South America' },
  SR: { name: 'Suriname', code: 'sr', region: 'South America' },
  FK: { name: 'Falkland Islands', code: 'fk', region: 'South America' },
  
  // Central America & Caribbean
  GT: { name: 'Guatemala', code: 'gt', region: 'Central America' },
  BZ: { name: 'Belize', code: 'bz', region: 'Central America' },
  HN: { name: 'Honduras', code: 'hn', region: 'Central America' },
  SV: { name: 'El Salvador', code: 'sv', region: 'Central America' },
  NI: { name: 'Nicaragua', code: 'ni', region: 'Central America' },
  CR: { name: 'Costa Rica', code: 'cr', region: 'Central America' },
  PA: { name: 'Panama', code: 'pa', region: 'Central America' },
  CU: { name: 'Cuba', code: 'cu', region: 'Caribbean' },
  JM: { name: 'Jamaica', code: 'jm', region: 'Caribbean' },
  HT: { name: 'Haiti', code: 'ht', region: 'Caribbean' },
  DO: { name: 'Dominican Republic', code: 'do', region: 'Caribbean' },
  PR: { name: 'Puerto Rico', code: 'pr', region: 'Caribbean' },
  TT: { name: 'Trinidad and Tobago', code: 'tt', region: 'Caribbean' },
  BB: { name: 'Barbados', code: 'bb', region: 'Caribbean' },
  GD: { name: 'Grenada', code: 'gd', region: 'Caribbean' },
  LC: { name: 'Saint Lucia', code: 'lc', region: 'Caribbean' },
  VC: { name: 'Saint Vincent and the Grenadines', code: 'vc', region: 'Caribbean' },
  AG: { name: 'Antigua and Barbuda', code: 'ag', region: 'Caribbean' },
  KN: { name: 'Saint Kitts and Nevis', code: 'kn', region: 'Caribbean' },
  DM: { name: 'Dominica', code: 'dm', region: 'Caribbean' },
  BS: { name: 'Bahamas', code: 'bs', region: 'Caribbean' },
  
  // Special Territories & Dependencies
  HK: { name: 'Hong Kong', code: 'hk', region: 'Asia' },
  MO: { name: 'Macau', code: 'mo', region: 'Asia' },
  TW: { name: 'Taiwan', code: 'tw', region: 'Asia' },
  PR: { name: 'Puerto Rico', code: 'pr', region: 'Caribbean' },
  GU: { name: 'Guam', code: 'gu', region: 'Oceania' },
  MP: { name: 'Northern Mariana Islands', code: 'mp', region: 'Oceania' },
  AS: { name: 'American Samoa', code: 'as', region: 'Oceania' },
  VI: { name: 'U.S. Virgin Islands', code: 'vi', region: 'Caribbean' },
  FM: { name: 'Micronesia', code: 'fm', region: 'Oceania' },
  MH: { name: 'Marshall Islands', code: 'mh', region: 'Oceania' },
  PW: { name: 'Palau', code: 'pw', region: 'Oceania' },
  KI: { name: 'Kiribati', code: 'ki', region: 'Oceania' },
  TV: { name: 'Tuvalu', code: 'tv', region: 'Oceania' },
  NR: { name: 'Nauru', code: 'nr', region: 'Oceania' },
  WS: { name: 'Samoa', code: 'ws', region: 'Oceania' },
  TO: { name: 'Tonga', code: 'to', region: 'Oceania' },
  CK: { name: 'Cook Islands', code: 'ck', region: 'Oceania' },
  NU: { name: 'Niue', code: 'nu', region: 'Oceania' },
  TK: { name: 'Tokelau', code: 'tk', region: 'Oceania' },
  WF: { name: 'Wallis and Futuna', code: 'wf', region: 'Oceania' },
  NC: { name: 'New Caledonia', code: 'nc', region: 'Oceania' },
  PF: { name: 'French Polynesia', code: 'pf', region: 'Oceania' },
  RE: { name: 'Réunion', code: 're', region: 'Africa' },
  YT: { name: 'Mayotte', code: 'yt', region: 'Africa' },
  GP: { name: 'Guadeloupe', code: 'gp', region: 'Caribbean' },
  MQ: { name: 'Martinique', code: 'mq', region: 'Caribbean' },
  GF: { name: 'French Guiana', code: 'gf', region: 'South America' },
  BL: { name: 'Saint Barthélemy', code: 'bl', region: 'Caribbean' },
  MF: { name: 'Saint Martin', code: 'mf', region: 'Caribbean' },
  PM: { name: 'Saint Pierre and Miquelon', code: 'pm', region: 'North America' },
  GL: { name: 'Greenland', code: 'gl', region: 'North America' },
  FO: { name: 'Faroe Islands', code: 'fo', region: 'Europe' },
  AX: { name: 'Åland Islands', code: 'ax', region: 'Europe' },
  SX: { name: 'Sint Maarten', code: 'sx', region: 'Caribbean' },
  CW: { name: 'Curaçao', code: 'cw', region: 'Caribbean' },
  BQ: { name: 'Caribbean Netherlands', code: 'bq', region: 'Caribbean' },
  AW: { name: 'Aruba', code: 'aw', region: 'Caribbean' },
  KY: { name: 'Cayman Islands', code: 'ky', region: 'Caribbean' },
  TC: { name: 'Turks and Caicos Islands', code: 'tc', region: 'Caribbean' },
  VG: { name: 'British Virgin Islands', code: 'vg', region: 'Caribbean' },
  AI: { name: 'Anguilla', code: 'ai', region: 'Caribbean' },
  MS: { name: 'Montserrat', code: 'ms', region: 'Caribbean' },
  BM: { name: 'Bermuda', code: 'bm', region: 'North America' },
  GI: { name: 'Gibraltar', code: 'gi', region: 'Europe' },
  AD: { name: 'Andorra', code: 'ad', region: 'Europe' },
  MC: { name: 'Monaco', code: 'mc', region: 'Europe' },
  LI: { name: 'Liechtenstein', code: 'li', region: 'Europe' },
  SM: { name: 'San Marino', code: 'sm', region: 'Europe' },
  VA: { name: 'Vatican City', code: 'va', region: 'Europe' },
  MT: { name: 'Malta', code: 'mt', region: 'Europe' },
  CY: { name: 'Cyprus', code: 'cy', region: 'Europe' },
  IS: { name: 'Iceland', code: 'is', region: 'Europe' },
  NO: { name: 'Norway', code: 'no', region: 'Europe' },
  SE: { name: 'Sweden', code: 'se', region: 'Europe' },
  FI: { name: 'Finland', code: 'fi', region: 'Europe' },
  DK: { name: 'Denmark', code: 'dk', region: 'Europe' },
  EE: { name: 'Estonia', code: 'ee', region: 'Europe' },
  LV: { name: 'Latvia', code: 'lv', region: 'Europe' },
  LT: { name: 'Lithuania', code: 'lt', region: 'Europe' },
  PL: { name: 'Poland', code: 'pl', region: 'Europe' },
  CZ: { name: 'Czech Republic', code: 'cz', region: 'Europe' },
  SK: { name: 'Slovakia', code: 'sk', region: 'Europe' },
  HU: { name: 'Hungary', code: 'hu', region: 'Europe' },
  RO: { name: 'Romania', code: 'ro', region: 'Europe' },
  BG: { name: 'Bulgaria', code: 'bg', region: 'Europe' },
  HR: { name: 'Croatia', code: 'hr', region: 'Europe' },
  SI: { name: 'Slovenia', code: 'si', region: 'Europe' },
  RS: { name: 'Serbia', code: 'rs', region: 'Europe' },
  ME: { name: 'Montenegro', code: 'me', region: 'Europe' },
  BA: { name: 'Bosnia and Herzegovina', code: 'ba', region: 'Europe' },
  MK: { name: 'North Macedonia', code: 'mk', region: 'Europe' },
  AL: { name: 'Albania', code: 'al', region: 'Europe' },
  GR: { name: 'Greece', code: 'gr', region: 'Europe' },
  TR: { name: 'Turkey', code: 'tr', region: 'Europe' },
  GE: { name: 'Georgia', code: 'ge', region: 'Europe' },
  AM: { name: 'Armenia', code: 'am', region: 'Europe' },
  AZ: { name: 'Azerbaijan', code: 'az', region: 'Europe' },
  RU: { name: 'Russia', code: 'ru', region: 'Europe' },
  BY: { name: 'Belarus', code: 'by', region: 'Europe' },
  UA: { name: 'Ukraine', code: 'ua', region: 'Europe' },
  MD: { name: 'Moldova', code: 'md', region: 'Europe' },
  KZ: { name: 'Kazakhstan', code: 'kz', region: 'Asia' },
  UZ: { name: 'Uzbekistan', code: 'uz', region: 'Asia' },
  KG: { name: 'Kyrgyzstan', code: 'kg', region: 'Asia' },
  TJ: { name: 'Tajikistan', code: 'tj', region: 'Asia' },
  TM: { name: 'Turkmenistan', code: 'tm', region: 'Asia' },
  AF: { name: 'Afghanistan', code: 'af', region: 'Asia' },
  PK: { name: 'Pakistan', code: 'pk', region: 'Asia' },
  IN: { name: 'India', code: 'in', region: 'Asia' },
  BD: { name: 'Bangladesh', code: 'bd', region: 'Asia' },
  NP: { name: 'Nepal', code: 'np', region: 'Asia' },
  BT: { name: 'Bhutan', code: 'bt', region: 'Asia' },
  MM: { name: 'Myanmar', code: 'mm', region: 'Asia' },
  TH: { name: 'Thailand', code: 'th', region: 'Asia' },
  LA: { name: 'Laos', code: 'la', region: 'Asia' },
  VN: { name: 'Vietnam', code: 'vn', region: 'Asia' },
  KH: { name: 'Cambodia', code: 'kh', region: 'Asia' },
  MY: { name: 'Malaysia', code: 'my', region: 'Asia' },
  SG: { name: 'Singapore', code: 'sg', region: 'Asia' },
  BN: { name: 'Brunei', code: 'bn', region: 'Asia' },
  ID: { name: 'Indonesia', code: 'id', region: 'Asia' },
  PH: { name: 'Philippines', code: 'ph', region: 'Asia' },
  TL: { name: 'Timor-Leste', code: 'tl', region: 'Asia' },
  PG: { name: 'Papua New Guinea', code: 'pg', region: 'Oceania' },
  FJ: { name: 'Fiji', code: 'fj', region: 'Oceania' },
  VU: { name: 'Vanuatu', code: 'vu', region: 'Oceania' },
  NC: { name: 'New Caledonia', code: 'nc', region: 'Oceania' },
  PF: { name: 'French Polynesia', code: 'pf', region: 'Oceania' },
  WS: { name: 'Samoa', code: 'ws', region: 'Oceania' },
  TO: { name: 'Tonga', code: 'to', region: 'Oceania' },
  CK: { name: 'Cook Islands', code: 'ck', region: 'Oceania' },
  NU: { name: 'Niue', code: 'nu', region: 'Oceania' },
  TK: { name: 'Tokelau', code: 'tk', region: 'Oceania' },
  WF: { name: 'Wallis and Futuna', code: 'wf', region: 'Oceania' },
  KI: { name: 'Kiribati', code: 'ki', region: 'Oceania' },
  TV: { name: 'Tuvalu', code: 'tv', region: 'Oceania' },
  NR: { name: 'Nauru', code: 'nr', region: 'Oceania' },
  MH: { name: 'Marshall Islands', code: 'mh', region: 'Oceania' },
  FM: { name: 'Micronesia', code: 'fm', region: 'Oceania' },
  PW: { name: 'Palau', code: 'pw', region: 'Oceania' },
  GU: { name: 'Guam', code: 'gu', region: 'Oceania' },
  MP: { name: 'Northern Mariana Islands', code: 'mp', region: 'Oceania' },
  AS: { name: 'American Samoa', code: 'as', region: 'Oceania' },
  PR: { name: 'Puerto Rico', code: 'pr', region: 'Caribbean' },
  VI: { name: 'U.S. Virgin Islands', code: 'vi', region: 'Caribbean' },
  CU: { name: 'Cuba', code: 'cu', region: 'Caribbean' },
  JM: { name: 'Jamaica', code: 'jm', region: 'Caribbean' },
  HT: { name: 'Haiti', code: 'ht', region: 'Caribbean' },
  DO: { name: 'Dominican Republic', code: 'do', region: 'Caribbean' },
  TT: { name: 'Trinidad and Tobago', code: 'tt', region: 'Caribbean' },
  BB: { name: 'Barbados', code: 'bb', region: 'Caribbean' },
  GD: { name: 'Grenada', code: 'gd', region: 'Caribbean' },
  LC: { name: 'Saint Lucia', code: 'lc', region: 'Caribbean' },
  VC: { name: 'Saint Vincent and the Grenadines', code: 'vc', region: 'Caribbean' },
  AG: { name: 'Antigua and Barbuda', code: 'ag', region: 'Caribbean' },
  KN: { name: 'Saint Kitts and Nevis', code: 'kn', region: 'Caribbean' },
  DM: { name: 'Dominica', code: 'dm', region: 'Caribbean' },
  BS: { name: 'Bahamas', code: 'bs', region: 'Caribbean' },
  TC: { name: 'Turks and Caicos Islands', code: 'tc', region: 'Caribbean' },
  KY: { name: 'Cayman Islands', code: 'ky', region: 'Caribbean' },
  VG: { name: 'British Virgin Islands', code: 'vg', region: 'Caribbean' },
  AI: { name: 'Anguilla', code: 'ai', region: 'Caribbean' },
  MS: { name: 'Montserrat', code: 'ms', region: 'Caribbean' },
  BM: { name: 'Bermuda', code: 'bm', region: 'North America' },
  GL: { name: 'Greenland', code: 'gl', region: 'North America' },
  FO: { name: 'Faroe Islands', code: 'fo', region: 'Europe' },
  AX: { name: 'Åland Islands', code: 'ax', region: 'Europe' },
  SX: { name: 'Sint Maarten', code: 'sx', region: 'Caribbean' },
  CW: { name: 'Curaçao', code: 'cw', region: 'Caribbean' },
  BQ: { name: 'Caribbean Netherlands', code: 'bq', region: 'Caribbean' },
  AW: { name: 'Aruba', code: 'aw', region: 'Caribbean' },
  RE: { name: 'Réunion', code: 're', region: 'Africa' },
  YT: { name: 'Mayotte', code: 'yt', region: 'Africa' },
  GP: { name: 'Guadeloupe', code: 'gp', region: 'Caribbean' },
  MQ: { name: 'Martinique', code: 'mq', region: 'Caribbean' },
  GF: { name: 'French Guiana', code: 'gf', region: 'South America' },
  BL: { name: 'Saint Barthélemy', code: 'bl', region: 'Caribbean' },
  MF: { name: 'Saint Martin', code: 'mf', region: 'Caribbean' },
  PM: { name: 'Saint Pierre and Miquelon', code: 'pm', region: 'North America' },
  GI: { name: 'Gibraltar', code: 'gi', region: 'Europe' },
  AD: { name: 'Andorra', code: 'ad', region: 'Europe' },
  MC: { name: 'Monaco', code: 'mc', region: 'Europe' },
  LI: { name: 'Liechtenstein', code: 'li', region: 'Europe' },
  SM: { name: 'San Marino', code: 'sm', region: 'Europe' },
  VA: { name: 'Vatican City', code: 'va', region: 'Europe' },
  GE: { name: 'Georgia', code: 'ge', region: 'Europe' },
  AM: { name: 'Armenia', code: 'am', region: 'Europe' },
  AZ: { name: 'Azerbaijan', code: 'az', region: 'Europe' },
  BT: { name: 'Bhutan', code: 'bt', region: 'Asia' },
  BN: { name: 'Brunei', code: 'bn', region: 'Asia' },
  TL: { name: 'Timor-Leste', code: 'tl', region: 'Asia' }
};

// Utility functions
export const getFlagUrl = (countryCode, size = 32) => {
  const code = countryCode?.toLowerCase() || 'us';
  return `/assets/flags/${code}-${size}.png`;
};

export const getCountryName = (countryCode) => {
  return countryFlags[countryCode?.toUpperCase()]?.name || 'Unknown';
};

export const getCountryRegion = (countryCode) => {
  return countryFlags[countryCode?.toUpperCase()]?.region || 'Unknown';
};

export const getCountriesByRegion = () => {
  const regions = {};
  Object.entries(countryFlags).forEach(([code, country]) => {
    if (!regions[country.region]) {
      regions[country.region] = [];
    }
    regions[country.region].push({ code, ...country });
  });
  return regions;
};

export const searchCountries = (query) => {
  const searchTerm = query.toLowerCase();
  return Object.entries(countryFlags)
    .filter(([code, country]) => 
      country.name.toLowerCase().includes(searchTerm) ||
      code.toLowerCase().includes(searchTerm)
    )
    .map(([code, country]) => ({ code, ...country }));
};

export const getPopularCountries = () => {
  // Return commonly used countries for quick selection
  const popularCodes = ['US', 'GB', 'DE', 'FR', 'JP', 'CA', 'AU', 'SG', 'NL', 'CH'];
  return popularCodes.map(code => ({ code, ...countryFlags[code] }));
};

// Flag size constants
export const FLAG_SIZES = {
  SMALL: 24,
  MEDIUM: 32,
  LARGE: 48,
  XLARGE: 64
};

// Default fallback
export const DEFAULT_COUNTRY = {
  code: 'US',
  name: 'United States',
  region: 'North America'
};
